### ISSUE TITLE
./link.sh: line 497: /usr/bin/clang++-12: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by HighCommander4** [elfshaker/manyclangs#8]
I tried to follow the instructions at https://github.com/elfshaker/manyclangs#x86-64 to run a version of clang from 2022-05 on an x86_64 machine, but when I got to the last step, I got the following error:

```console
$ docker run --rm -it  --mount type=bind,source="$(pwd)",target=/elfshaker manyclangs-qemu-aarch64  bash -c 'bash ./link.sh --and-run clang --version'
./link.sh: line 497: /usr/bin/clang++-12: cannot execute binary file: Exec format error
./link.sh had non-zero exit. Setting TRACE=1 in environment may help determine what is wrong.
```

**Comment by pwaller** [comment]
The message:
```
/usr/bin/clang++-12: cannot execute binary file: Exec format error
```
suggests that running the aarch64 `/usr/bin/clang++-12` is not working inside the container, and that aarch64 emulation isn't set up. I suspect manyclang's docs are missing a step.

If you're on Ubuntu, try installing the `binfmt-support` package and please report back if that helps. If you're not on Ubuntu please provide additional information about how you're trying to run.

The [docker docs](https://docs.docker.com/build/building/multi-platform/) for multi-platform support also suggest `docker run --privileged --rm tonistiigi/binfmt --install all`, but that seems a bit of an unpleasant hammer to use if installing binfmt-support is all that's needed.

**Comment by HighCommander4** [comment]
> If you're on Ubuntu, try installing the `binfmt-support` package and please report back if that helps.

That did not help. (I'm on Debian stable, not Ubuntu, but I imagine that doesn't make a big difference.)

> The [docker docs](https://docs.docker.com/build/building/multi-platform/) for multi-platform support also suggest `docker run --privileged --rm tonistiigi/binfmt --install all`, but that seems a bit of an unpleasant hammer to use if installing binfmt-support is all that's needed.

That did resolve the issue, thanks!

**Comment by pwaller** [comment]
Hmm, it would be good to understand why that fixed it, if it is really necessary. I'd appreciate any help here so we can update the documentation for others.

**Comment by HighCommander4** [comment]
I'm happy to test additional things to help investigate, but I would appreciate guidance on what to test since I don't particularly understand the issue myself.

**Comment by pwaller** [comment]
Reading https://wiki.debian.org/Arm64Qemu: Do you have an `update-binfmts --display` you can run?

I posit that tonistiigi's binfmt updater should be unnecessary on Debian. You should be able to install `binfmt-support` and `qemu-user-static`: https://wiki.debian.org/QemuUserEmulation

Then you should have what you need. You cold try `docker run --privileged --rm tonistiigi/binfmt --uninstall all` and then reinstall (dpkg-reconfigure if necessary) those packages.

**Comment by pwaller** [comment]
If `update-binfmts --display` is empty after the uninstall, and then reports something at the end of this process, and everything works, then you're good.

If this fails, I believe rerunning tonistiigi's binfmt installer again will get you back to your currently functioning state.

**Comment by HighCommander4** [comment]
> I posit that tonistiigi's binfmt updater should be unnecessary on Debian. You should be able to install `binfmt-support` and `qemu-user-static`: https://wiki.debian.org/QemuUserEmulation

Confirmed, additionally installing `qemu-user-static` is what seems to have made the difference.

**Comment by pwaller** [comment]
If you fancy contributing would you mind sending a PR the doc to include those critical instructions in a way that would have worked for you? No worries if not :)

**Comment by HighCommander4** [comment]
Sure, sent out https://github.com/elfshaker/manyclangs/pull/10

**Comment by pwaller** [comment]
Thanks for getting to the bottom of this :)
